### ISSUE TITLE
Can Vnum have multiple properties?

### ISSUE THREAD

**Issue by fedotxxl** [AmirKamali/Flutter_Vnum#2]
You've got an example:

```
String color(){
    if (value == CarType.sedan.value) {
      return "Green";
    }else if (value == CarType.suv.value) {
      return "Orange";
    }else if (value == CarType.truck.value) {
      return "Yellow";
    }
    return "Unknown";
  }
```

Is it possible to make color as a property of enum item and rewrite method as:

```
String color(){
  return this._color;
}
```

?

Will soon serialization / deserializiation work in this case?

**Comment by AmirKamali** [comment]
The answer is yes, since Vnum is a class by nature, you have the flexibility to declare properties. 

You also can serialize/deserialize however It's recommended to keep it simple for enum use and do your serialization/deserialization at parent object level.
